// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club.sql

package db

import (
	"context"
	"time"
)

const createClub = `-- name: CreateClub :one
INSERT INTO clubs (
    id,
    name,
    balance,
    start_balance,
    base_fee,
    auto_tip_enabled,
    couples_mode_enabled,
    user_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at
`

type CreateClubParams struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	Balance            int32     `json:"balance"`
	StartBalance       int32     `json:"start_balance"`
	BaseFee            int32     `json:"base_fee"`
	AutoTipEnabled     bool      `json:"auto_tip_enabled"`
	CouplesModeEnabled bool      `json:"couples_mode_enabled"`
	UserID             string    `json:"user_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, createClub,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.StartBalance,
		arg.BaseFee,
		arg.AutoTipEnabled,
		arg.CouplesModeEnabled,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.BaseFee,
		&i.AutoTipEnabled,
		&i.CouplesModeEnabled,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClub = `-- name: DeleteClub :exec
DELETE FROM clubs
WHERE id = $1
`

func (q *Queries) DeleteClub(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClub, id)
	return err
}

const getAllClubs = `-- name: GetAllClubs :many
SELECT id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at FROM clubs
ORDER BY created_at DESC
`

func (q *Queries) GetAllClubs(ctx context.Context) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getAllClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.StartBalance,
			&i.BaseFee,
			&i.AutoTipEnabled,
			&i.CouplesModeEnabled,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubByID = `-- name: GetClubByID :one
SELECT id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at FROM clubs
WHERE id = $1
`

func (q *Queries) GetClubByID(ctx context.Context, id string) (Club, error) {
	row := q.db.QueryRowContext(ctx, getClubByID, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.BaseFee,
		&i.AutoTipEnabled,
		&i.CouplesModeEnabled,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClubsByUserID = `-- name: GetClubsByUserID :many
SELECT id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at FROM clubs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetClubsByUserID(ctx context.Context, userID string) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getClubsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.StartBalance,
			&i.BaseFee,
			&i.AutoTipEnabled,
			&i.CouplesModeEnabled,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubsForUser = `-- name: GetClubsForUser :many
SELECT id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at FROM clubs c
WHERE c.user_id = $1
   OR EXISTS (
       SELECT 1 FROM players p
       WHERE p.club_id = c.id AND p.user_id = $1
   )
ORDER BY c.created_at DESC
`

func (q *Queries) GetClubsForUser(ctx context.Context, userID string) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getClubsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Club
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.StartBalance,
			&i.BaseFee,
			&i.AutoTipEnabled,
			&i.CouplesModeEnabled,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClub = `-- name: UpdateClub :one
UPDATE clubs
SET
    name = $1,
    balance = $2,
    start_balance = $3,
    base_fee = $4,
    auto_tip_enabled = $5,
    couples_mode_enabled = $6,
    updated_at = $7
WHERE id = $8
RETURNING id, name, balance, start_balance, base_fee, auto_tip_enabled, couples_mode_enabled, user_id, created_at, updated_at
`

type UpdateClubParams struct {
	Name               string    `json:"name"`
	Balance            int32     `json:"balance"`
	StartBalance       int32     `json:"start_balance"`
	BaseFee            int32     `json:"base_fee"`
	AutoTipEnabled     bool      `json:"auto_tip_enabled"`
	CouplesModeEnabled bool      `json:"couples_mode_enabled"`
	UpdatedAt          time.Time `json:"updated_at"`
	ID                 string    `json:"id"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error) {
	row := q.db.QueryRowContext(ctx, updateClub,
		arg.Name,
		arg.Balance,
		arg.StartBalance,
		arg.BaseFee,
		arg.AutoTipEnabled,
		arg.CouplesModeEnabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.BaseFee,
		&i.AutoTipEnabled,
		&i.CouplesModeEnabled,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClubBalance = `-- name: UpdateClubBalance :exec
UPDATE clubs
SET balance = $1, updated_at = $2
WHERE id = $3
`

type UpdateClubBalanceParams struct {
	Balance   int32     `json:"balance"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateClubBalance(ctx context.Context, arg UpdateClubBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateClubBalance, arg.Balance, arg.UpdatedAt, arg.ID)
	return err
}
