// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competition.sql

package db

import (
	"context"
	"time"
)

const createCompetition = `-- name: CreateCompetition :one
INSERT INTO competitions (
    id,
    club_id,
    name,
    scoring_type,
    is_gender_specific,
    display_order,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, club_id, name, scoring_type, is_gender_specific, display_order, created_at, updated_at
`

type CreateCompetitionParams struct {
	ID               string    `json:"id"`
	ClubID           string    `json:"club_id"`
	Name             string    `json:"name"`
	ScoringType      string    `json:"scoring_type"`
	IsGenderSpecific bool      `json:"is_gender_specific"`
	DisplayOrder     int32     `json:"display_order"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, createCompetition,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.ScoringType,
		arg.IsGenderSpecific,
		arg.DisplayOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.ScoringType,
		&i.IsGenderSpecific,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompetition = `-- name: DeleteCompetition :exec
DELETE FROM competitions WHERE id = $1
`

func (q *Queries) DeleteCompetition(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCompetition, id)
	return err
}

const getCompetitionByID = `-- name: GetCompetitionByID :one
SELECT id, club_id, name, scoring_type, is_gender_specific, display_order, created_at, updated_at FROM competitions WHERE id = $1
`

func (q *Queries) GetCompetitionByID(ctx context.Context, id string) (Competition, error) {
	row := q.db.QueryRowContext(ctx, getCompetitionByID, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.ScoringType,
		&i.IsGenderSpecific,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompetitionsByClubID = `-- name: GetCompetitionsByClubID :many
SELECT id, club_id, name, scoring_type, is_gender_specific, display_order, created_at, updated_at FROM competitions
WHERE club_id = $1
ORDER BY display_order ASC, created_at ASC
`

func (q *Queries) GetCompetitionsByClubID(ctx context.Context, clubID string) ([]Competition, error) {
	rows, err := q.db.QueryContext(ctx, getCompetitionsByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Competition
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.ScoringType,
			&i.IsGenderSpecific,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxCompetitionDisplayOrderByClubID = `-- name: GetMaxCompetitionDisplayOrderByClubID :one
SELECT COALESCE(MAX(display_order), 0)::int as max_display_order
FROM competitions
WHERE club_id = $1
`

func (q *Queries) GetMaxCompetitionDisplayOrderByClubID(ctx context.Context, clubID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxCompetitionDisplayOrderByClubID, clubID)
	var max_display_order int32
	err := row.Scan(&max_display_order)
	return max_display_order, err
}

const updateCompetition = `-- name: UpdateCompetition :one
UPDATE competitions
SET
    name = $1,
    scoring_type = $2,
    is_gender_specific = $3,
    display_order = $4,
    updated_at = $5
WHERE id = $6
RETURNING id, club_id, name, scoring_type, is_gender_specific, display_order, created_at, updated_at
`

type UpdateCompetitionParams struct {
	Name             string    `json:"name"`
	ScoringType      string    `json:"scoring_type"`
	IsGenderSpecific bool      `json:"is_gender_specific"`
	DisplayOrder     int32     `json:"display_order"`
	UpdatedAt        time.Time `json:"updated_at"`
	ID               string    `json:"id"`
}

func (q *Queries) UpdateCompetition(ctx context.Context, arg UpdateCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, updateCompetition,
		arg.Name,
		arg.ScoringType,
		arg.IsGenderSpecific,
		arg.DisplayOrder,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.ScoringType,
		&i.IsGenderSpecific,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
