// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gameday.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkGameDayExistsByClubAndDate = `-- name: CheckGameDayExistsByClubAndDate :one
SELECT COUNT(*) > 0 as exists
FROM game_days
WHERE club_id = $1 AND date = $2
`

type CheckGameDayExistsByClubAndDateParams struct {
	ClubID string    `json:"club_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) CheckGameDayExistsByClubAndDate(ctx context.Context, arg CheckGameDayExistsByClubAndDateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkGameDayExistsByClubAndDate, arg.ClubID, arg.Date)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createGameDay = `-- name: CreateGameDay :one

INSERT INTO game_days (id, club_id, date, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, club_id, date, notes, created_at, updated_at
`

type CreateGameDayParams struct {
	ID        string         `json:"id"`
	ClubID    string         `json:"club_id"`
	Date      time.Time      `json:"date"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// ==================== GAME DAYS ====================
func (q *Queries) CreateGameDay(ctx context.Context, arg CreateGameDayParams) (GameDay, error) {
	row := q.db.QueryRowContext(ctx, createGameDay,
		arg.ID,
		arg.ClubID,
		arg.Date,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GameDay
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Date,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGameDayFee = `-- name: CreateGameDayFee :one

INSERT INTO game_day_fees (
    id, game_day_participant_id, penalty_type_id,
    penalty_type_name, penalty_type_description, penalty_type_price,
    count, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, game_day_participant_id, penalty_type_id, penalty_type_name, penalty_type_description, penalty_type_price, count, created_at, updated_at
`

type CreateGameDayFeeParams struct {
	ID                     string         `json:"id"`
	GameDayParticipantID   string         `json:"game_day_participant_id"`
	PenaltyTypeID          string         `json:"penalty_type_id"`
	PenaltyTypeName        string         `json:"penalty_type_name"`
	PenaltyTypeDescription sql.NullString `json:"penalty_type_description"`
	PenaltyTypePrice       int32          `json:"penalty_type_price"`
	Count                  int32          `json:"count"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

// ==================== FEES ====================
func (q *Queries) CreateGameDayFee(ctx context.Context, arg CreateGameDayFeeParams) (GameDayFee, error) {
	row := q.db.QueryRowContext(ctx, createGameDayFee,
		arg.ID,
		arg.GameDayParticipantID,
		arg.PenaltyTypeID,
		arg.PenaltyTypeName,
		arg.PenaltyTypeDescription,
		arg.PenaltyTypePrice,
		arg.Count,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GameDayFee
	err := row.Scan(
		&i.ID,
		&i.GameDayParticipantID,
		&i.PenaltyTypeID,
		&i.PenaltyTypeName,
		&i.PenaltyTypeDescription,
		&i.PenaltyTypePrice,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGameDayParticipant = `-- name: CreateGameDayParticipant :one

INSERT INTO game_day_participants (id, game_day_id, player_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, game_day_id, player_id, created_at
`

type CreateGameDayParticipantParams struct {
	ID        string    `json:"id"`
	GameDayID string    `json:"game_day_id"`
	PlayerID  string    `json:"player_id"`
	CreatedAt time.Time `json:"created_at"`
}

// ==================== PARTICIPANTS ====================
func (q *Queries) CreateGameDayParticipant(ctx context.Context, arg CreateGameDayParticipantParams) (GameDayParticipant, error) {
	row := q.db.QueryRowContext(ctx, createGameDayParticipant,
		arg.ID,
		arg.GameDayID,
		arg.PlayerID,
		arg.CreatedAt,
	)
	var i GameDayParticipant
	err := row.Scan(
		&i.ID,
		&i.GameDayID,
		&i.PlayerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllFeesByParticipant = `-- name: DeleteAllFeesByParticipant :exec
DELETE FROM game_day_fees WHERE game_day_participant_id = $1
`

func (q *Queries) DeleteAllFeesByParticipant(ctx context.Context, gameDayParticipantID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllFeesByParticipant, gameDayParticipantID)
	return err
}

const deleteAllParticipantsByGameDay = `-- name: DeleteAllParticipantsByGameDay :exec
DELETE FROM game_day_participants WHERE game_day_id = $1
`

func (q *Queries) DeleteAllParticipantsByGameDay(ctx context.Context, gameDayID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllParticipantsByGameDay, gameDayID)
	return err
}

const deleteGameDay = `-- name: DeleteGameDay :exec
DELETE FROM game_days WHERE id = $1
`

func (q *Queries) DeleteGameDay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGameDay, id)
	return err
}

const deleteGameDayFee = `-- name: DeleteGameDayFee :exec
DELETE FROM game_day_fees WHERE id = $1
`

func (q *Queries) DeleteGameDayFee(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGameDayFee, id)
	return err
}

const deleteGameDayFeeByParticipantAndType = `-- name: DeleteGameDayFeeByParticipantAndType :exec
DELETE FROM game_day_fees 
WHERE game_day_participant_id = $1 AND penalty_type_id = $2
`

type DeleteGameDayFeeByParticipantAndTypeParams struct {
	GameDayParticipantID string `json:"game_day_participant_id"`
	PenaltyTypeID        string `json:"penalty_type_id"`
}

func (q *Queries) DeleteGameDayFeeByParticipantAndType(ctx context.Context, arg DeleteGameDayFeeByParticipantAndTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteGameDayFeeByParticipantAndType, arg.GameDayParticipantID, arg.PenaltyTypeID)
	return err
}

const deleteGameDayParticipant = `-- name: DeleteGameDayParticipant :exec
DELETE FROM game_day_participants 
WHERE game_day_id = $1 AND player_id = $2
`

type DeleteGameDayParticipantParams struct {
	GameDayID string `json:"game_day_id"`
	PlayerID  string `json:"player_id"`
}

func (q *Queries) DeleteGameDayParticipant(ctx context.Context, arg DeleteGameDayParticipantParams) error {
	_, err := q.db.ExecContext(ctx, deleteGameDayParticipant, arg.GameDayID, arg.PlayerID)
	return err
}

const getGameDayByID = `-- name: GetGameDayByID :one
SELECT id, club_id, date, notes, created_at, updated_at FROM game_days WHERE id = $1
`

func (q *Queries) GetGameDayByID(ctx context.Context, id string) (GameDay, error) {
	row := q.db.QueryRowContext(ctx, getGameDayByID, id)
	var i GameDay
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Date,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameDayFeesByGameDay = `-- name: GetGameDayFeesByGameDay :many
SELECT gdf.id, gdf.game_day_participant_id, gdf.penalty_type_id, gdf.penalty_type_name, gdf.penalty_type_description, gdf.penalty_type_price, gdf.count, gdf.created_at, gdf.updated_at, gdp.player_id, p.name as player_name
FROM game_day_fees gdf
JOIN game_day_participants gdp ON gdp.id = gdf.game_day_participant_id
JOIN players p ON p.id = gdp.player_id
WHERE gdp.game_day_id = $1
ORDER BY p.name ASC, gdf.penalty_type_name ASC
`

type GetGameDayFeesByGameDayRow struct {
	ID                     string         `json:"id"`
	GameDayParticipantID   string         `json:"game_day_participant_id"`
	PenaltyTypeID          string         `json:"penalty_type_id"`
	PenaltyTypeName        string         `json:"penalty_type_name"`
	PenaltyTypeDescription sql.NullString `json:"penalty_type_description"`
	PenaltyTypePrice       int32          `json:"penalty_type_price"`
	Count                  int32          `json:"count"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
	PlayerID               string         `json:"player_id"`
	PlayerName             string         `json:"player_name"`
}

func (q *Queries) GetGameDayFeesByGameDay(ctx context.Context, gameDayID string) ([]GetGameDayFeesByGameDayRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameDayFeesByGameDay, gameDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameDayFeesByGameDayRow
	for rows.Next() {
		var i GetGameDayFeesByGameDayRow
		if err := rows.Scan(
			&i.ID,
			&i.GameDayParticipantID,
			&i.PenaltyTypeID,
			&i.PenaltyTypeName,
			&i.PenaltyTypeDescription,
			&i.PenaltyTypePrice,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerID,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDayFeesByParticipant = `-- name: GetGameDayFeesByParticipant :many
SELECT id, game_day_participant_id, penalty_type_id, penalty_type_name, penalty_type_description, penalty_type_price, count, created_at, updated_at FROM game_day_fees 
WHERE game_day_participant_id = $1
ORDER BY penalty_type_name ASC
`

func (q *Queries) GetGameDayFeesByParticipant(ctx context.Context, gameDayParticipantID string) ([]GameDayFee, error) {
	rows, err := q.db.QueryContext(ctx, getGameDayFeesByParticipant, gameDayParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameDayFee
	for rows.Next() {
		var i GameDayFee
		if err := rows.Scan(
			&i.ID,
			&i.GameDayParticipantID,
			&i.PenaltyTypeID,
			&i.PenaltyTypeName,
			&i.PenaltyTypeDescription,
			&i.PenaltyTypePrice,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDayParticipants = `-- name: GetGameDayParticipants :many
SELECT gdp.id, gdp.game_day_id, gdp.player_id, gdp.created_at, p.name as player_name
FROM game_day_participants gdp
JOIN players p ON p.id = gdp.player_id
WHERE gdp.game_day_id = $1
ORDER BY gdp.created_at ASC
`

type GetGameDayParticipantsRow struct {
	ID         string    `json:"id"`
	GameDayID  string    `json:"game_day_id"`
	PlayerID   string    `json:"player_id"`
	CreatedAt  time.Time `json:"created_at"`
	PlayerName string    `json:"player_name"`
}

func (q *Queries) GetGameDayParticipants(ctx context.Context, gameDayID string) ([]GetGameDayParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getGameDayParticipants, gameDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameDayParticipantsRow
	for rows.Next() {
		var i GetGameDayParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameDayID,
			&i.PlayerID,
			&i.CreatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameDaysByClubID = `-- name: GetGameDaysByClubID :many
SELECT id, club_id, date, notes, created_at, updated_at FROM game_days 
WHERE club_id = $1 
ORDER BY date DESC
`

func (q *Queries) GetGameDaysByClubID(ctx context.Context, clubID string) ([]GameDay, error) {
	rows, err := q.db.QueryContext(ctx, getGameDaysByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameDay
	for rows.Next() {
		var i GameDay
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Date,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantByGameDayAndPlayer = `-- name: GetParticipantByGameDayAndPlayer :one
SELECT id, game_day_id, player_id, created_at FROM game_day_participants 
WHERE game_day_id = $1 AND player_id = $2
`

type GetParticipantByGameDayAndPlayerParams struct {
	GameDayID string `json:"game_day_id"`
	PlayerID  string `json:"player_id"`
}

func (q *Queries) GetParticipantByGameDayAndPlayer(ctx context.Context, arg GetParticipantByGameDayAndPlayerParams) (GameDayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getParticipantByGameDayAndPlayer, arg.GameDayID, arg.PlayerID)
	var i GameDayParticipant
	err := row.Scan(
		&i.ID,
		&i.GameDayID,
		&i.PlayerID,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameDay = `-- name: UpdateGameDay :one
UPDATE game_days 
SET date = $2, notes = $3, updated_at = $4
WHERE id = $1
RETURNING id, club_id, date, notes, created_at, updated_at
`

type UpdateGameDayParams struct {
	ID        string         `json:"id"`
	Date      time.Time      `json:"date"`
	Notes     sql.NullString `json:"notes"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateGameDay(ctx context.Context, arg UpdateGameDayParams) (GameDay, error) {
	row := q.db.QueryRowContext(ctx, updateGameDay,
		arg.ID,
		arg.Date,
		arg.Notes,
		arg.UpdatedAt,
	)
	var i GameDay
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Date,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGameDayFee = `-- name: UpdateGameDayFee :one
UPDATE game_day_fees
SET count = $2, updated_at = $3
WHERE id = $1
RETURNING id, game_day_participant_id, penalty_type_id, penalty_type_name, penalty_type_description, penalty_type_price, count, created_at, updated_at
`

type UpdateGameDayFeeParams struct {
	ID        string    `json:"id"`
	Count     int32     `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateGameDayFee(ctx context.Context, arg UpdateGameDayFeeParams) (GameDayFee, error) {
	row := q.db.QueryRowContext(ctx, updateGameDayFee, arg.ID, arg.Count, arg.UpdatedAt)
	var i GameDayFee
	err := row.Scan(
		&i.ID,
		&i.GameDayParticipantID,
		&i.PenaltyTypeID,
		&i.PenaltyTypeName,
		&i.PenaltyTypeDescription,
		&i.PenaltyTypePrice,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGameDayFee = `-- name: UpsertGameDayFee :one
INSERT INTO game_day_fees (
    id, game_day_participant_id, penalty_type_id,
    penalty_type_name, penalty_type_description, penalty_type_price,
    count, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (game_day_participant_id, penalty_type_id)
DO UPDATE SET 
    count = EXCLUDED.count,
    updated_at = EXCLUDED.updated_at
RETURNING id, game_day_participant_id, penalty_type_id, penalty_type_name, penalty_type_description, penalty_type_price, count, created_at, updated_at
`

type UpsertGameDayFeeParams struct {
	ID                     string         `json:"id"`
	GameDayParticipantID   string         `json:"game_day_participant_id"`
	PenaltyTypeID          string         `json:"penalty_type_id"`
	PenaltyTypeName        string         `json:"penalty_type_name"`
	PenaltyTypeDescription sql.NullString `json:"penalty_type_description"`
	PenaltyTypePrice       int32          `json:"penalty_type_price"`
	Count                  int32          `json:"count"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertGameDayFee(ctx context.Context, arg UpsertGameDayFeeParams) (GameDayFee, error) {
	row := q.db.QueryRowContext(ctx, upsertGameDayFee,
		arg.ID,
		arg.GameDayParticipantID,
		arg.PenaltyTypeID,
		arg.PenaltyTypeName,
		arg.PenaltyTypeDescription,
		arg.PenaltyTypePrice,
		arg.Count,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GameDayFee
	err := row.Scan(
		&i.ID,
		&i.GameDayParticipantID,
		&i.PenaltyTypeID,
		&i.PenaltyTypeName,
		&i.PenaltyTypeDescription,
		&i.PenaltyTypePrice,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
