// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Club struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Balance   int32     `json:"balance"`
	BaseFee   int32     `json:"base_fee"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type GameDay struct {
	ID        string         `json:"id"`
	ClubID    string         `json:"club_id"`
	Date      time.Time      `json:"date"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type GameDayFee struct {
	ID                     string         `json:"id"`
	GameDayParticipantID   string         `json:"game_day_participant_id"`
	PenaltyTypeID          string         `json:"penalty_type_id"`
	PenaltyTypeName        string         `json:"penalty_type_name"`
	PenaltyTypeDescription sql.NullString `json:"penalty_type_description"`
	PenaltyTypePrice       int32          `json:"penalty_type_price"`
	Count                  int32          `json:"count"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type GameDayParticipant struct {
	ID        string    `json:"id"`
	GameDayID string    `json:"game_day_id"`
	PlayerID  string    `json:"player_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PenaltyType struct {
	ID           string         `json:"id"`
	ClubID       string         `json:"club_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        int32          `json:"price"`
	DisplayOrder int32          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	ReplacedByID *string        `json:"replaced_by_id"`
}

type Player struct {
	ID           string    `json:"id"`
	ClubID       string    `json:"club_id"`
	UserID       *string   `json:"user_id"`
	RoleID       *string   `json:"role_id"`
	Name         string    `json:"name"`
	Balance      int32     `json:"balance"`
	StartBalance int32     `json:"start_balance"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Role struct {
	ID          string    `json:"id"`
	ClubID      string    `json:"club_id"`
	Name        string    `json:"name"`
	PaysBaseFee bool      `json:"pays_base_fee"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	ID             string    `json:"id"`
	RoleID         string    `json:"role_id"`
	EntityType     string    `json:"entity_type"`
	PermissionType string    `json:"permission_type"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
