// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Club struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	Balance            int32     `json:"balance"`
	StartBalance       int32     `json:"start_balance"`
	BaseFee            int32     `json:"base_fee"`
	AutoTipEnabled     bool      `json:"auto_tip_enabled"`
	CouplesModeEnabled bool      `json:"couples_mode_enabled"`
	UserID             string    `json:"user_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Competition struct {
	ID               string    `json:"id"`
	ClubID           string    `json:"club_id"`
	Name             string    `json:"name"`
	ScoringType      string    `json:"scoring_type"`
	IsGenderSpecific bool      `json:"is_gender_specific"`
	DisplayOrder     int32     `json:"display_order"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type GameDay struct {
	ID        string         `json:"id"`
	ClubID    string         `json:"club_id"`
	Date      time.Time      `json:"date"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type GameDayCompetitionValue struct {
	ID                   string    `json:"id"`
	GameDayParticipantID string    `json:"game_day_participant_id"`
	CompetitionID        string    `json:"competition_id"`
	Value                int32     `json:"value"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type GameDayFee struct {
	ID                     string         `json:"id"`
	GameDayParticipantID   string         `json:"game_day_participant_id"`
	PenaltyTypeID          string         `json:"penalty_type_id"`
	PenaltyTypeName        string         `json:"penalty_type_name"`
	PenaltyTypeDescription sql.NullString `json:"penalty_type_description"`
	PenaltyTypePrice       int32          `json:"penalty_type_price"`
	Count                  int32          `json:"count"`
	QuantityScale          int32          `json:"quantity_scale"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type GameDayParticipant struct {
	ID        string    `json:"id"`
	GameDayID string    `json:"game_day_id"`
	PlayerID  string    `json:"player_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PasswordResetToken struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type PenaltyType struct {
	ID                    string         `json:"id"`
	ClubID                string         `json:"club_id"`
	Name                  string         `json:"name"`
	Description           sql.NullString `json:"description"`
	Price                 int32          `json:"price"`
	DisplayOrder          int32          `json:"display_order"`
	AllowsDecimalQuantity bool           `json:"allows_decimal_quantity"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
	ReplacedByID          *string        `json:"replaced_by_id"`
}

type Player struct {
	ID           string         `json:"id"`
	ClubID       string         `json:"club_id"`
	UserID       *string        `json:"user_id"`
	RoleID       *string        `json:"role_id"`
	Name         string         `json:"name"`
	Balance      int32          `json:"balance"`
	StartBalance int32          `json:"start_balance"`
	Gender       sql.NullString `json:"gender"`
	Inactive     bool           `json:"inactive"`
	PartnerID    *string        `json:"partner_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type PlayerInvitation struct {
	ID         string       `json:"id"`
	PlayerID   string       `json:"player_id"`
	Email      string       `json:"email"`
	Token      string       `json:"token"`
	ExpiresAt  time.Time    `json:"expires_at"`
	AcceptedAt sql.NullTime `json:"accepted_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type Role struct {
	ID          string    `json:"id"`
	ClubID      string    `json:"club_id"`
	Name        string    `json:"name"`
	PaysBaseFee bool      `json:"pays_base_fee"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	ID             string    `json:"id"`
	RoleID         string    `json:"role_id"`
	EntityType     string    `json:"entity_type"`
	PermissionType string    `json:"permission_type"`
	CreatedAt      time.Time `json:"created_at"`
}

type Transaction struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	TransactionDate     time.Time      `json:"transaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
