// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: penalty_type.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPenaltyType = `-- name: CreatePenaltyType :one
INSERT INTO penalty_types (
    id,
    club_id,
    name,
    description,
    price,
    display_order,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, club_id, name, description, price, display_order, created_at, updated_at, deleted_at, replaced_by_id
`

type CreatePenaltyTypeParams struct {
	ID           string         `json:"id"`
	ClubID       string         `json:"club_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        int32          `json:"price"`
	DisplayOrder int32          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error) {
	row := q.db.QueryRowContext(ctx, createPenaltyType,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.DisplayOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const deletePenaltyType = `-- name: DeletePenaltyType :exec
UPDATE penalty_types
SET deleted_at = $1
WHERE id = $2 AND deleted_at IS NULL
`

type DeletePenaltyTypeParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	ID        string       `json:"id"`
}

func (q *Queries) DeletePenaltyType(ctx context.Context, arg DeletePenaltyTypeParams) error {
	_, err := q.db.ExecContext(ctx, deletePenaltyType, arg.DeletedAt, arg.ID)
	return err
}

const getMaxDisplayOrderByClubID = `-- name: GetMaxDisplayOrderByClubID :one
SELECT COALESCE(MAX(display_order), 0) as max_display_order
FROM penalty_types
WHERE club_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaxDisplayOrderByClubID(ctx context.Context, clubID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxDisplayOrderByClubID, clubID)
	var max_display_order interface{}
	err := row.Scan(&max_display_order)
	return max_display_order, err
}

const getPenaltyTypeByID = `-- name: GetPenaltyTypeByID :one
SELECT id, club_id, name, description, price, display_order, created_at, updated_at, deleted_at, replaced_by_id FROM penalty_types
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPenaltyTypeByID(ctx context.Context, id string) (PenaltyType, error) {
	row := q.db.QueryRowContext(ctx, getPenaltyTypeByID, id)
	var i PenaltyType
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReplacedByID,
	)
	return i, err
}

const getPenaltyTypesByClubID = `-- name: GetPenaltyTypesByClubID :many
SELECT id, club_id, name, description, price, display_order, created_at, updated_at, deleted_at, replaced_by_id FROM penalty_types
WHERE club_id = $1 AND deleted_at IS NULL
ORDER BY display_order ASC, created_at ASC
`

func (q *Queries) GetPenaltyTypesByClubID(ctx context.Context, clubID string) ([]PenaltyType, error) {
	rows, err := q.db.QueryContext(ctx, getPenaltyTypesByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyType
	for rows.Next() {
		var i PenaltyType
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReplacedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPenaltyTypeAsReplaced = `-- name: MarkPenaltyTypeAsReplaced :exec
UPDATE penalty_types
SET deleted_at = $1,
    replaced_by_id = $2
WHERE id = $3 AND deleted_at IS NULL
`

type MarkPenaltyTypeAsReplacedParams struct {
	DeletedAt    sql.NullTime `json:"deleted_at"`
	ReplacedByID *string      `json:"replaced_by_id"`
	ID           string       `json:"id"`
}

func (q *Queries) MarkPenaltyTypeAsReplaced(ctx context.Context, arg MarkPenaltyTypeAsReplacedParams) error {
	_, err := q.db.ExecContext(ctx, markPenaltyTypeAsReplaced, arg.DeletedAt, arg.ReplacedByID, arg.ID)
	return err
}

const updatePenaltyTypeDisplayOrder = `-- name: UpdatePenaltyTypeDisplayOrder :exec
UPDATE penalty_types
SET display_order = $1,
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePenaltyTypeDisplayOrderParams struct {
	DisplayOrder int32     `json:"display_order"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdatePenaltyTypeDisplayOrder(ctx context.Context, arg UpdatePenaltyTypeDisplayOrderParams) error {
	_, err := q.db.ExecContext(ctx, updatePenaltyTypeDisplayOrder, arg.DisplayOrder, arg.UpdatedAt, arg.ID)
	return err
}
