// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (
    id,
    club_id,
    user_id,
    role_id,
    name,
    balance,
    start_balance,
    gender,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, club_id, user_id, role_id, name, balance, start_balance, gender, created_at, updated_at
`

type CreatePlayerParams struct {
	ID           string         `json:"id"`
	ClubID       string         `json:"club_id"`
	UserID       *string        `json:"user_id"`
	RoleID       *string        `json:"role_id"`
	Name         string         `json:"name"`
	Balance      int32          `json:"balance"`
	StartBalance int32          `json:"start_balance"`
	Gender       sql.NullString `json:"gender"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.ID,
		arg.ClubID,
		arg.UserID,
		arg.RoleID,
		arg.Name,
		arg.Balance,
		arg.StartBalance,
		arg.Gender,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.RoleID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, club_id, user_id, role_id, name, balance, start_balance, gender, created_at, updated_at FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.RoleID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByUserIDAndClubID = `-- name: GetPlayerByUserIDAndClubID :one
SELECT id, club_id, user_id, role_id, name, balance, start_balance, gender, created_at, updated_at FROM players
WHERE user_id = $1 AND club_id = $2
`

type GetPlayerByUserIDAndClubIDParams struct {
	UserID *string `json:"user_id"`
	ClubID string  `json:"club_id"`
}

func (q *Queries) GetPlayerByUserIDAndClubID(ctx context.Context, arg GetPlayerByUserIDAndClubIDParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUserIDAndClubID, arg.UserID, arg.ClubID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.RoleID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayersByClubID = `-- name: GetPlayersByClubID :many
SELECT id, club_id, user_id, role_id, name, balance, start_balance, gender, created_at, updated_at FROM players
WHERE club_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPlayersByClubID(ctx context.Context, clubID string) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.UserID,
			&i.RoleID,
			&i.Name,
			&i.Balance,
			&i.StartBalance,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET
    name = $1,
    balance = $2,
    start_balance = $3,
    user_id = $4,
    role_id = $5,
    gender = $6,
    updated_at = $7
WHERE id = $8
RETURNING id, club_id, user_id, role_id, name, balance, start_balance, gender, created_at, updated_at
`

type UpdatePlayerParams struct {
	Name         string         `json:"name"`
	Balance      int32          `json:"balance"`
	StartBalance int32          `json:"start_balance"`
	UserID       *string        `json:"user_id"`
	RoleID       *string        `json:"role_id"`
	Gender       sql.NullString `json:"gender"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayer,
		arg.Name,
		arg.Balance,
		arg.StartBalance,
		arg.UserID,
		arg.RoleID,
		arg.Gender,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.UserID,
		&i.RoleID,
		&i.Name,
		&i.Balance,
		&i.StartBalance,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayerBalance = `-- name: UpdatePlayerBalance :exec
UPDATE players
SET balance = $1, updated_at = $2
WHERE id = $3
`

type UpdatePlayerBalanceParams struct {
	Balance   int32     `json:"balance"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlayerBalance(ctx context.Context, arg UpdatePlayerBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerBalance, arg.Balance, arg.UpdatedAt, arg.ID)
	return err
}
