// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_invitation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const acceptPlayerInvitation = `-- name: AcceptPlayerInvitation :exec
UPDATE player_invitations
SET accepted_at = $1
WHERE id = $2
`

type AcceptPlayerInvitationParams struct {
	AcceptedAt sql.NullTime `json:"accepted_at"`
	ID         string       `json:"id"`
}

func (q *Queries) AcceptPlayerInvitation(ctx context.Context, arg AcceptPlayerInvitationParams) error {
	_, err := q.db.ExecContext(ctx, acceptPlayerInvitation, arg.AcceptedAt, arg.ID)
	return err
}

const createPlayerInvitation = `-- name: CreatePlayerInvitation :one
INSERT INTO player_invitations (
    id,
    player_id,
    email,
    token,
    expires_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, player_id, email, token, expires_at, accepted_at, created_at
`

type CreatePlayerInvitationParams struct {
	ID        string    `json:"id"`
	PlayerID  string    `json:"player_id"`
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePlayerInvitation(ctx context.Context, arg CreatePlayerInvitationParams) (PlayerInvitation, error) {
	row := q.db.QueryRowContext(ctx, createPlayerInvitation,
		arg.ID,
		arg.PlayerID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i PlayerInvitation
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerInvitationByID = `-- name: GetPlayerInvitationByID :one
SELECT id, player_id, email, token, expires_at, accepted_at, created_at FROM player_invitations
WHERE id = $1
`

func (q *Queries) GetPlayerInvitationByID(ctx context.Context, id string) (PlayerInvitation, error) {
	row := q.db.QueryRowContext(ctx, getPlayerInvitationByID, id)
	var i PlayerInvitation
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerInvitationByToken = `-- name: GetPlayerInvitationByToken :one
SELECT id, player_id, email, token, expires_at, accepted_at, created_at FROM player_invitations
WHERE token = $1
`

func (q *Queries) GetPlayerInvitationByToken(ctx context.Context, token string) (PlayerInvitation, error) {
	row := q.db.QueryRowContext(ctx, getPlayerInvitationByToken, token)
	var i PlayerInvitation
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerInvitationsByPlayerID = `-- name: GetPlayerInvitationsByPlayerID :many
SELECT id, player_id, email, token, expires_at, accepted_at, created_at FROM player_invitations
WHERE player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPlayerInvitationsByPlayerID(ctx context.Context, playerID string) ([]PlayerInvitation, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerInvitationsByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerInvitation
	for rows.Next() {
		var i PlayerInvitation
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Email,
			&i.Token,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
