// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) (RolePermission, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClub(ctx context.Context, id string) error
	DeletePenaltyType(ctx context.Context, arg DeletePenaltyTypeParams) error
	DeletePlayer(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	GetAllClubs(ctx context.Context) ([]Club, error)
	GetClubByID(ctx context.Context, id string) (Club, error)
	GetClubsByUserID(ctx context.Context, userID string) ([]Club, error)
	GetMaxDisplayOrderByClubID(ctx context.Context, clubID string) (interface{}, error)
	GetPenaltyTypeByID(ctx context.Context, id string) (PenaltyType, error)
	GetPenaltyTypesByClubID(ctx context.Context, clubID string) ([]PenaltyType, error)
	GetPlayerByID(ctx context.Context, id string) (Player, error)
	GetPlayersByClubID(ctx context.Context, clubID string) ([]Player, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID string) ([]RolePermission, error)
	GetRolesByClubID(ctx context.Context, clubID string) ([]Role, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	HasRolePermission(ctx context.Context, arg HasRolePermissionParams) (bool, error)
	MarkPenaltyTypeAsReplaced(ctx context.Context, arg MarkPenaltyTypeAsReplacedParams) error
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error)
	UpdatePenaltyTypeDisplayOrder(ctx context.Context, arg UpdatePenaltyTypeDisplayOrderParams) error
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
