// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AcceptPlayerInvitation(ctx context.Context, arg AcceptPlayerInvitationParams) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) (RolePermission, error)
	CheckGameDayExistsByClubAndDate(ctx context.Context, arg CheckGameDayExistsByClubAndDateParams) (bool, error)
	CountTransactionsByClub(ctx context.Context, clubID string) (int64, error)
	CountTransactionsByPlayer(ctx context.Context, arg CountTransactionsByPlayerParams) (int64, error)
	CountTransactionsByType(ctx context.Context, arg CountTransactionsByTypeParams) (int64, error)
	CreateClub(ctx context.Context, arg CreateClubParams) (Club, error)
	CreateCompetition(ctx context.Context, arg CreateCompetitionParams) (Competition, error)
	// ==================== GAME DAYS ====================
	CreateGameDay(ctx context.Context, arg CreateGameDayParams) (GameDay, error)
	// ==================== COMPETITION VALUES ====================
	CreateGameDayCompetitionValue(ctx context.Context, arg CreateGameDayCompetitionValueParams) (GameDayCompetitionValue, error)
	// ==================== FEES ====================
	CreateGameDayFee(ctx context.Context, arg CreateGameDayFeeParams) (GameDayFee, error)
	// ==================== PARTICIPANTS ====================
	CreateGameDayParticipant(ctx context.Context, arg CreateGameDayParticipantParams) (GameDayParticipant, error)
	CreatePenaltyType(ctx context.Context, arg CreatePenaltyTypeParams) (PenaltyType, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreatePlayerInvitation(ctx context.Context, arg CreatePlayerInvitationParams) (PlayerInvitation, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ==================== TRANSACTIONS ====================
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllCompetitionValuesByParticipant(ctx context.Context, gameDayParticipantID string) error
	DeleteAllFeesByParticipant(ctx context.Context, gameDayParticipantID string) error
	DeleteAllParticipantsByGameDay(ctx context.Context, gameDayID string) error
	DeleteClub(ctx context.Context, id string) error
	DeleteCompetition(ctx context.Context, id string) error
	DeleteGameDay(ctx context.Context, id string) error
	DeleteGameDayCompetitionValue(ctx context.Context, id string) error
	DeleteGameDayCompetitionValueByParticipantAndCompetition(ctx context.Context, arg DeleteGameDayCompetitionValueByParticipantAndCompetitionParams) error
	DeleteGameDayFee(ctx context.Context, id string) error
	DeleteGameDayFeeByParticipantAndType(ctx context.Context, arg DeleteGameDayFeeByParticipantAndTypeParams) error
	DeleteGameDayParticipant(ctx context.Context, arg DeleteGameDayParticipantParams) error
	DeletePenaltyType(ctx context.Context, arg DeletePenaltyTypeParams) error
	DeletePlayer(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, id string) error
	DeleteTransaction(ctx context.Context, id string) error
	GetAllClubs(ctx context.Context) ([]Club, error)
	GetClubByID(ctx context.Context, id string) (Club, error)
	GetClubsByUserID(ctx context.Context, userID string) ([]Club, error)
	GetCompetitionByID(ctx context.Context, id string) (Competition, error)
	GetCompetitionsByClubID(ctx context.Context, clubID string) ([]Competition, error)
	GetGameDayByID(ctx context.Context, id string) (GameDay, error)
	GetGameDayCompetitionValuesByGameDay(ctx context.Context, gameDayID string) ([]GetGameDayCompetitionValuesByGameDayRow, error)
	GetGameDayCompetitionValuesByParticipant(ctx context.Context, gameDayParticipantID string) ([]GameDayCompetitionValue, error)
	GetGameDayFeesByGameDay(ctx context.Context, gameDayID string) ([]GetGameDayFeesByGameDayRow, error)
	GetGameDayFeesByParticipant(ctx context.Context, gameDayParticipantID string) ([]GameDayFee, error)
	GetGameDayParticipants(ctx context.Context, gameDayID string) ([]GetGameDayParticipantsRow, error)
	// ==================== SUMMARIES ====================
	GetGameDaySummariesByClubID(ctx context.Context, clubID string) ([]GetGameDaySummariesByClubIDRow, error)
	GetGameDayTransactionSummary(ctx context.Context, gameDayID *string) (GetGameDayTransactionSummaryRow, error)
	GetGameDaysByClubID(ctx context.Context, clubID string) ([]GameDay, error)
	GetMaxCompetitionDisplayOrderByClubID(ctx context.Context, clubID string) (int32, error)
	GetMaxDisplayOrderByClubID(ctx context.Context, clubID string) (interface{}, error)
	GetParticipantByGameDayAndPlayer(ctx context.Context, arg GetParticipantByGameDayAndPlayerParams) (GameDayParticipant, error)
	GetPenaltyTypeByID(ctx context.Context, id string) (PenaltyType, error)
	GetPenaltyTypesByClubID(ctx context.Context, clubID string) ([]PenaltyType, error)
	GetPlayerByID(ctx context.Context, id string) (Player, error)
	GetPlayerByUserIDAndClubID(ctx context.Context, arg GetPlayerByUserIDAndClubIDParams) (Player, error)
	GetPlayerInvitationByID(ctx context.Context, id string) (PlayerInvitation, error)
	GetPlayerInvitationByToken(ctx context.Context, token string) (PlayerInvitation, error)
	GetPlayerInvitationsByPlayerID(ctx context.Context, playerID string) ([]PlayerInvitation, error)
	GetPlayersByClubID(ctx context.Context, clubID string) ([]Player, error)
	GetRoleByID(ctx context.Context, id string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID string) ([]RolePermission, error)
	GetRolesByClubID(ctx context.Context, clubID string) ([]Role, error)
	GetTransactionByGameDayFee(ctx context.Context, gameDayFeeID *string) (Transaction, error)
	GetTransactionByID(ctx context.Context, id string) (GetTransactionByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	HasRolePermission(ctx context.Context, arg HasRolePermissionParams) (bool, error)
	ListTransactionsByClub(ctx context.Context, arg ListTransactionsByClubParams) ([]ListTransactionsByClubRow, error)
	ListTransactionsByGameDay(ctx context.Context, gameDayID *string) ([]ListTransactionsByGameDayRow, error)
	ListTransactionsByPlayer(ctx context.Context, arg ListTransactionsByPlayerParams) ([]ListTransactionsByPlayerRow, error)
	ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]ListTransactionsByTypeRow, error)
	MarkPenaltyTypeAsReplaced(ctx context.Context, arg MarkPenaltyTypeAsReplacedParams) error
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	SumTransactionsByClub(ctx context.Context, clubID string) (interface{}, error)
	SumTransactionsByPlayer(ctx context.Context, playerID *string) (interface{}, error)
	UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error)
	UpdateCompetition(ctx context.Context, arg UpdateCompetitionParams) (Competition, error)
	UpdateGameDay(ctx context.Context, arg UpdateGameDayParams) (GameDay, error)
	UpdateGameDayFee(ctx context.Context, arg UpdateGameDayFeeParams) (GameDayFee, error)
	UpdatePenaltyTypeDisplayOrder(ctx context.Context, arg UpdatePenaltyTypeDisplayOrderParams) error
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdatePlayerBalance(ctx context.Context, arg UpdatePlayerBalanceParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpsertGameDayCompetitionValue(ctx context.Context, arg UpsertGameDayCompetitionValueParams) (GameDayCompetitionValue, error)
	UpsertGameDayFee(ctx context.Context, arg UpsertGameDayFeeParams) (GameDayFee, error)
}

var _ Querier = (*Queries)(nil)
