// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"
	"time"
)

const addRolePermission = `-- name: AddRolePermission :one
INSERT INTO role_permissions (
    id,
    role_id,
    entity_type,
    permission_type,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, role_id, entity_type, permission_type, created_at
`

type AddRolePermissionParams struct {
	ID             string    `json:"id"`
	RoleID         string    `json:"role_id"`
	EntityType     string    `json:"entity_type"`
	PermissionType string    `json:"permission_type"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRowContext(ctx, addRolePermission,
		arg.ID,
		arg.RoleID,
		arg.EntityType,
		arg.PermissionType,
		arg.CreatedAt,
	)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.EntityType,
		&i.PermissionType,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id,
    club_id,
    name,
    pays_base_fee,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, club_id, name, pays_base_fee, created_at, updated_at
`

type CreateRoleParams struct {
	ID          string    `json:"id"`
	ClubID      string    `json:"club_id"`
	Name        string    `json:"name"`
	PaysBaseFee bool      `json:"pays_base_fee"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.ID,
		arg.ClubID,
		arg.Name,
		arg.PaysBaseFee,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.PaysBaseFee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, club_id, name, pays_base_fee, created_at, updated_at FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.PaysBaseFee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT id, role_id, entity_type, permission_type, created_at FROM role_permissions
WHERE role_id = $1
ORDER BY entity_type, permission_type
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID string) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.EntityType,
			&i.PermissionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByClubID = `-- name: GetRolesByClubID :many
SELECT id, club_id, name, pays_base_fee, created_at, updated_at FROM roles
WHERE club_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRolesByClubID(ctx context.Context, clubID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.Name,
			&i.PaysBaseFee,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasRolePermission = `-- name: HasRolePermission :one
SELECT COUNT(*) > 0
FROM role_permissions
WHERE role_id = $1 AND entity_type = $2 AND permission_type = $3
`

type HasRolePermissionParams struct {
	RoleID         string `json:"role_id"`
	EntityType     string `json:"entity_type"`
	PermissionType string `json:"permission_type"`
}

func (q *Queries) HasRolePermission(ctx context.Context, arg HasRolePermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasRolePermission, arg.RoleID, arg.EntityType, arg.PermissionType)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND entity_type = $2 AND permission_type = $3
`

type RemoveRolePermissionParams struct {
	RoleID         string `json:"role_id"`
	EntityType     string `json:"entity_type"`
	PermissionType string `json:"permission_type"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, removeRolePermission, arg.RoleID, arg.EntityType, arg.PermissionType)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET
    name = $1,
    pays_base_fee = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, club_id, name, pays_base_fee, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        string    `json:"name"`
	PaysBaseFee bool      `json:"pays_base_fee"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.Name,
		arg.PaysBaseFee,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.Name,
		&i.PaysBaseFee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
