// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countTransactionsByClub = `-- name: CountTransactionsByClub :one
SELECT COUNT(*) FROM transactions WHERE club_id = $1
`

func (q *Queries) CountTransactionsByClub(ctx context.Context, clubID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByClub, clubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByPlayer = `-- name: CountTransactionsByPlayer :one
SELECT COUNT(*) FROM transactions 
WHERE club_id = $1 AND player_id = $2
`

type CountTransactionsByPlayerParams struct {
	ClubID   string  `json:"club_id"`
	PlayerID *string `json:"player_id"`
}

func (q *Queries) CountTransactionsByPlayer(ctx context.Context, arg CountTransactionsByPlayerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByPlayer, arg.ClubID, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsByType = `-- name: CountTransactionsByType :one
SELECT COUNT(*) FROM transactions 
WHERE club_id = $1 AND transaction_type = $2
`

type CountTransactionsByTypeParams struct {
	ClubID          string `json:"club_id"`
	TransactionType string `json:"transaction_type"`
}

func (q *Queries) CountTransactionsByType(ctx context.Context, arg CountTransactionsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByType, arg.ClubID, arg.TransactionType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
    id, club_id, player_id, transaction_type,
    amount, description, game_day_fee_id, game_day_id,
    player_balance_before, player_balance_after,
    club_balance_before, club_balance_after,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, club_id, player_id, transaction_type, amount, description, game_day_fee_id, game_day_id, player_balance_before, player_balance_after, club_balance_before, club_balance_after, created_at, updated_at
`

type CreateTransactionParams struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

// ==================== TRANSACTIONS ====================
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.ClubID,
		arg.PlayerID,
		arg.TransactionType,
		arg.Amount,
		arg.Description,
		arg.GameDayFeeID,
		arg.GameDayID,
		arg.PlayerBalanceBefore,
		arg.PlayerBalanceAfter,
		arg.ClubBalanceBefore,
		arg.ClubBalanceAfter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.GameDayFeeID,
		&i.GameDayID,
		&i.PlayerBalanceBefore,
		&i.PlayerBalanceAfter,
		&i.ClubBalanceBefore,
		&i.ClubBalanceAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getGameDayTransactionSummary = `-- name: GetGameDayTransactionSummary :one
SELECT 
    COALESCE(SUM(CASE WHEN transaction_type = 'base_fee' THEN ABS(amount) ELSE 0 END), 0) as base_fee_total,
    COALESCE(SUM(CASE WHEN transaction_type = 'fee' THEN ABS(amount) ELSE 0 END), 0) as fee_total,
    COUNT(CASE WHEN transaction_type = 'base_fee' THEN 1 END) as base_fee_count,
    COUNT(CASE WHEN transaction_type = 'fee' THEN 1 END) as fee_count
FROM transactions
WHERE game_day_id = $1
`

type GetGameDayTransactionSummaryRow struct {
	BaseFeeTotal interface{} `json:"base_fee_total"`
	FeeTotal     interface{} `json:"fee_total"`
	BaseFeeCount int64       `json:"base_fee_count"`
	FeeCount     int64       `json:"fee_count"`
}

func (q *Queries) GetGameDayTransactionSummary(ctx context.Context, gameDayID *string) (GetGameDayTransactionSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getGameDayTransactionSummary, gameDayID)
	var i GetGameDayTransactionSummaryRow
	err := row.Scan(
		&i.BaseFeeTotal,
		&i.FeeTotal,
		&i.BaseFeeCount,
		&i.FeeCount,
	)
	return i, err
}

const getTransactionByGameDayFee = `-- name: GetTransactionByGameDayFee :one
SELECT id, club_id, player_id, transaction_type, amount, description, game_day_fee_id, game_day_id, player_balance_before, player_balance_after, club_balance_before, club_balance_after, created_at, updated_at FROM transactions WHERE game_day_fee_id = $1
`

func (q *Queries) GetTransactionByGameDayFee(ctx context.Context, gameDayFeeID *string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByGameDayFee, gameDayFeeID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.GameDayFeeID,
		&i.GameDayID,
		&i.PlayerBalanceBefore,
		&i.PlayerBalanceAfter,
		&i.ClubBalanceBefore,
		&i.ClubBalanceAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.club_id, t.player_id, t.transaction_type, t.amount, t.description, t.game_day_fee_id, t.game_day_id, t.player_balance_before, t.player_balance_after, t.club_balance_before, t.club_balance_after, t.created_at, t.updated_at, p.name as player_name
FROM transactions t
LEFT JOIN players p ON p.id = t.player_id
WHERE t.id = $1
`

type GetTransactionByIDRow struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	PlayerName          sql.NullString `json:"player_name"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.GameDayFeeID,
		&i.GameDayID,
		&i.PlayerBalanceBefore,
		&i.PlayerBalanceAfter,
		&i.ClubBalanceBefore,
		&i.ClubBalanceAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayerName,
	)
	return i, err
}

const listTransactionsByClub = `-- name: ListTransactionsByClub :many
SELECT t.id, t.club_id, t.player_id, t.transaction_type, t.amount, t.description, t.game_day_fee_id, t.game_day_id, t.player_balance_before, t.player_balance_after, t.club_balance_before, t.club_balance_after, t.created_at, t.updated_at, p.name as player_name
FROM transactions t
LEFT JOIN players p ON p.id = t.player_id
WHERE t.club_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByClubParams struct {
	ClubID string `json:"club_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListTransactionsByClubRow struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	PlayerName          sql.NullString `json:"player_name"`
}

func (q *Queries) ListTransactionsByClub(ctx context.Context, arg ListTransactionsByClubParams) ([]ListTransactionsByClubRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByClub, arg.ClubID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByClubRow
	for rows.Next() {
		var i ListTransactionsByClubRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.PlayerID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.GameDayFeeID,
			&i.GameDayID,
			&i.PlayerBalanceBefore,
			&i.PlayerBalanceAfter,
			&i.ClubBalanceBefore,
			&i.ClubBalanceAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByGameDay = `-- name: ListTransactionsByGameDay :many
SELECT t.id, t.club_id, t.player_id, t.transaction_type, t.amount, t.description, t.game_day_fee_id, t.game_day_id, t.player_balance_before, t.player_balance_after, t.club_balance_before, t.club_balance_after, t.created_at, t.updated_at, p.name as player_name
FROM transactions t
LEFT JOIN players p ON p.id = t.player_id
WHERE t.game_day_id = $1
ORDER BY t.created_at ASC
`

type ListTransactionsByGameDayRow struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	PlayerName          sql.NullString `json:"player_name"`
}

func (q *Queries) ListTransactionsByGameDay(ctx context.Context, gameDayID *string) ([]ListTransactionsByGameDayRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByGameDay, gameDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByGameDayRow
	for rows.Next() {
		var i ListTransactionsByGameDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.PlayerID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.GameDayFeeID,
			&i.GameDayID,
			&i.PlayerBalanceBefore,
			&i.PlayerBalanceAfter,
			&i.ClubBalanceBefore,
			&i.ClubBalanceAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPlayer = `-- name: ListTransactionsByPlayer :many
SELECT t.id, t.club_id, t.player_id, t.transaction_type, t.amount, t.description, t.game_day_fee_id, t.game_day_id, t.player_balance_before, t.player_balance_after, t.club_balance_before, t.club_balance_after, t.created_at, t.updated_at, p.name as player_name
FROM transactions t
LEFT JOIN players p ON p.id = t.player_id
WHERE t.club_id = $1 AND t.player_id = $2
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByPlayerParams struct {
	ClubID   string  `json:"club_id"`
	PlayerID *string `json:"player_id"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

type ListTransactionsByPlayerRow struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	PlayerName          sql.NullString `json:"player_name"`
}

func (q *Queries) ListTransactionsByPlayer(ctx context.Context, arg ListTransactionsByPlayerParams) ([]ListTransactionsByPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByPlayer,
		arg.ClubID,
		arg.PlayerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByPlayerRow
	for rows.Next() {
		var i ListTransactionsByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.PlayerID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.GameDayFeeID,
			&i.GameDayID,
			&i.PlayerBalanceBefore,
			&i.PlayerBalanceAfter,
			&i.ClubBalanceBefore,
			&i.ClubBalanceAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT t.id, t.club_id, t.player_id, t.transaction_type, t.amount, t.description, t.game_day_fee_id, t.game_day_id, t.player_balance_before, t.player_balance_after, t.club_balance_before, t.club_balance_after, t.created_at, t.updated_at, p.name as player_name
FROM transactions t
LEFT JOIN players p ON p.id = t.player_id
WHERE t.club_id = $1 AND t.transaction_type = $2
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByTypeParams struct {
	ClubID          string `json:"club_id"`
	TransactionType string `json:"transaction_type"`
	Limit           int32  `json:"limit"`
	Offset          int32  `json:"offset"`
}

type ListTransactionsByTypeRow struct {
	ID                  string         `json:"id"`
	ClubID              string         `json:"club_id"`
	PlayerID            *string        `json:"player_id"`
	TransactionType     string         `json:"transaction_type"`
	Amount              int32          `json:"amount"`
	Description         sql.NullString `json:"description"`
	GameDayFeeID        *string        `json:"game_day_fee_id"`
	GameDayID           *string        `json:"game_day_id"`
	PlayerBalanceBefore sql.NullInt32  `json:"player_balance_before"`
	PlayerBalanceAfter  sql.NullInt32  `json:"player_balance_after"`
	ClubBalanceBefore   int32          `json:"club_balance_before"`
	ClubBalanceAfter    int32          `json:"club_balance_after"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	PlayerName          sql.NullString `json:"player_name"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]ListTransactionsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByType,
		arg.ClubID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByTypeRow
	for rows.Next() {
		var i ListTransactionsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.PlayerID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.GameDayFeeID,
			&i.GameDayID,
			&i.PlayerBalanceBefore,
			&i.PlayerBalanceAfter,
			&i.ClubBalanceBefore,
			&i.ClubBalanceAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionsByClub = `-- name: SumTransactionsByClub :one
SELECT COALESCE(SUM(
    CASE 
        WHEN transaction_type IN ('deposit', 'tip') THEN amount
        WHEN transaction_type = 'expense' THEN amount
        ELSE 0
    END
), 0) as total
FROM transactions
WHERE club_id = $1
`

func (q *Queries) SumTransactionsByClub(ctx context.Context, clubID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionsByClub, clubID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumTransactionsByPlayer = `-- name: SumTransactionsByPlayer :one
SELECT COALESCE(SUM(
    CASE 
        WHEN transaction_type IN ('base_fee', 'fee') THEN amount
        WHEN transaction_type = 'deposit' THEN -amount
        ELSE 0
    END
), 0) as total
FROM transactions
WHERE player_id = $1
`

func (q *Queries) SumTransactionsByPlayer(ctx context.Context, playerID *string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumTransactionsByPlayer, playerID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount = $2, description = $3, updated_at = $4
WHERE id = $1
RETURNING id, club_id, player_id, transaction_type, amount, description, game_day_fee_id, game_day_id, player_balance_before, player_balance_after, club_balance_before, club_balance_after, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          string         `json:"id"`
	Amount      int32          `json:"amount"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.PlayerID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.GameDayFeeID,
		&i.GameDayID,
		&i.PlayerBalanceBefore,
		&i.PlayerBalanceAfter,
		&i.ClubBalanceBefore,
		&i.ClubBalanceAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
